version: '3.8'

services:
  kleenpulse-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kleenpulse_africa_prod
    ports:
      - "80:80"
    restart: always
    environment:
      - NODE_ENV=production
