"""SourceKettle seed catalogue.

Products are mapped onto the real taxonomy in `data/taxonomy.json`, so the app
exercises the actual segment/attribute schema rather than a parallel one.

!! The UN numbers, grades and specs below are ILLUSTRATIVE seed data for
development. In production these must come from a verified supplier record and
the UN numbers must validate against a curated DG reference table -- which is
exactly what `DG_REFERENCE` below and `un_number_known()` enforce.
"""

from __future__ import annotations

# Curated dangerous-goods reference (stand-in for the `dg_reference` table).
# The engine validates UN numbers against this, never free-typed text.
DG_REFERENCE: dict[str, dict] = {
    "1789": {"psn": "HYDROCHLORIC ACID", "class": "8", "pg": ["II", "III"]},
    "1791": {"psn": "HYPOCHLORITE SOLUTION", "class": "8", "pg": ["II", "III"]},
    "1823": {"psn": "SODIUM HYDROXIDE, SOLID", "class": "8", "pg": ["II"]},
    "1824": {"psn": "SODIUM HYDROXIDE SOLUTION", "class": "8", "pg": ["II", "III"]},
    "1830": {"psn": "SULPHURIC ACID", "class": "8", "pg": ["II"]},
    "2031": {"psn": "NITRIC ACID", "class": "8", "pg": ["II", "III"]},
    "1719": {"psn": "CAUSTIC ALKALI LIQUID, N.O.S.", "class": "8", "pg": ["II", "III"]},
    "1219": {"psn": "ISOPROPANOL", "class": "3", "pg": ["II"]},
    "1230": {"psn": "METHANOL", "class": "3", "pg": ["II"]},
    "1173": {"psn": "ETHYL ACETATE", "class": "3", "pg": ["II"]},
    "3082": {"psn": "ENVIRONMENTALLY HAZARDOUS SUBSTANCE, LIQUID, N.O.S.",
             "class": "9", "pg": ["III"]},
    "3016": {"psn": "LIQUID PESTICIDE, TOXIC", "class": "6.1", "pg": ["I", "II", "III"]},
    "1805": {"psn": "PHOSPHORIC ACID, SOLUTION", "class": "8", "pg": ["III"]},
    "2695": {"psn": "SODIUM METABISULPHITE", "class": "8", "pg": ["III"]},
    "1170": {"psn": "ETHANOL", "class": "3", "pg": ["II", "III"]},
    # --- added with the generated catalogue; shipping names are the IMDG PSNs ---
    "1090": {"psn": "ACETONE", "class": "3", "pg": ["II"]},
    "1120": {"psn": "BUTANOLS", "class": "3", "pg": ["II", "III"]},
    "1123": {"psn": "BUTYL ACETATES", "class": "3", "pg": ["II", "III"]},
    "1193": {"psn": "ETHYL METHYL KETONE", "class": "3", "pg": ["II"]},
    "1245": {"psn": "METHYL ISOBUTYL KETONE", "class": "3", "pg": ["II"]},
    "1294": {"psn": "TOLUENE", "class": "3", "pg": ["II"]},
    "1307": {"psn": "XYLENES", "class": "3", "pg": ["II", "III"]},
    "1330": {"psn": "NAPHTHA, SOLVENT", "class": "3", "pg": ["II", "III"]},
    "1779": {"psn": "FORMIC ACID", "class": "8", "pg": ["II"]},
    "1813": {"psn": "POTASSIUM HYDROXIDE, SOLID", "class": "8", "pg": ["II"]},
    "1993": {"psn": "FLAMMABLE LIQUID, N.O.S.", "class": "3", "pg": ["I", "II", "III"]},
    "2014": {"psn": "HYDROGEN PEROXIDE, AQUEOUS SOLUTION", "class": "5.1", "pg": ["II", "III"]},
    "2331": {"psn": "ZINC CHLORIDE", "class": "8", "pg": ["III"]},
    "2489": {"psn": "METHYL MERCAPTAN-adjacent ISOCYANATE n.o.s. (polymeric MDI)",
             "class": "6.1", "pg": ["II"]},
    "2582": {"psn": "FERRIC CHLORIDE, SOLUTION", "class": "8", "pg": ["II", "III"]},
    "2584": {"psn": "ALKYLSULFONIC ACIDS, LIQUID", "class": "8", "pg": ["II", "III"]},
    "2672": {"psn": "AMMONIA SOLUTION", "class": "8", "pg": ["II", "III"]},
    "2789": {"psn": "ACETIC ACID, GLACIAL", "class": "8", "pg": ["II"]},
}


def un_number_known(un: str | None) -> bool:
    return un in DG_REFERENCE if un else False


_P = lambda **kw: kw  # readability helper


def _pack(unit, net_kg, un_rated=None, per_pallet=None):
    d = {"unit": unit, "net_weight_kg": net_kg}
    if un_rated:
        d["un_rated"] = un_rated
    if per_pallet:
        d["units_per_pallet"] = per_pallet
    return d


# --------------------------------------------------------------------------- #
# Catalogue. `segment` is the Taxonomy A node code.
# --------------------------------------------------------------------------- #
PRODUCTS: list[dict] = [
    # ============================ S1 BULK ================================== #
    _P(id="p-1001", sku="CAUS-FL98", name="Caustic Soda Flakes 98%", segment="S11.2",
       cas="1310-73-2", grade="industrial", form="flake", purity=98.0,
       un="1823", dg="8", pg="II", ghs=["GHS05", "GHS07"], flash=None, storage="SC-2",
       price=485, uom="kg", moq=1000, lead=7, origin="IN",
       packs=[_pack("25 kg bag", 25, per_pallet=40), _pack("1000 kg jumbo", 1000)],
       supplier="s1", docs=["SDS", "CoA"], note="Workhorse alkali. Never co-load with acids or hypochlorite."),
    _P(id="p-1002", sku="CAUS-LYE47", name="Caustic Soda Lye 47%", segment="S11.2",
       cas="1310-73-2", grade="industrial", form="liquid", purity=47.0,
       un="1824", dg="8", pg="II", ghs=["GHS05"], flash=None, storage="SC-2",
       price=340, uom="kg", moq=1250, lead=5, origin="NG",
       packs=[_pack("1250 kg IBC", 1250, "31HA1/Y1.8/100")],
       supplier="s2", docs=["SDS", "CoA"], note="Liquid dosing grade for water treatment and CIP."),
    _P(id="p-1003", sku="HCL-33", name="Hydrochloric Acid 33%", segment="S11.1",
       cas="7647-01-0", grade="technical", form="liquid", purity=33.0,
       un="1789", dg="8", pg="II", ghs=["GHS05", "GHS07"], flash=None, storage="SC-1",
       price=165, uom="kg", moq=1250, lead=5, origin="NG",
       packs=[_pack("1250 kg IBC", 1250, "31HA1/Y1.8/100")],
       supplier="s2", docs=["SDS", "CoA"], note="Storage class SC-1. Lethal if mixed with hypochlorite."),
    _P(id="p-1004", sku="H2SO4-98", name="Sulphuric Acid 98%", segment="S11.1",
       cas="7664-93-9", grade="technical", form="liquid", purity=98.0,
       un="1830", dg="8", pg="II", ghs=["GHS05"], flash=None, storage="SC-1",
       price=198, uom="kg", moq=1250, lead=6, origin="IN",
       packs=[_pack("1250 kg IBC", 1250, "31HA1/Y1.8/100")],
       supplier="s1", docs=["SDS", "CoA"]),
    _P(id="p-1005", sku="NAOCL-125", name="Sodium Hypochlorite 12.5%", segment="S11.3",
       cas="7681-52-9", grade="industrial", form="liquid", purity=12.5,
       un="1791", dg="8", pg="III", ghs=["GHS05", "GHS09"], flash=None, storage="SC-4",
       price=88, uom="kg", moq=1250, lead=4, origin="NG",
       packs=[_pack("1250 kg IBC", 1250, "31HA1/Y1.8/100")],
       supplier="s2", docs=["SDS", "CoA"], note="Oxidiser, SC-4. Chlorine gas evolves on contact with acid."),
    _P(id="p-1006", sku="SODA-DENSE", name="Soda Ash Dense", segment="S11.2",
       cas="497-19-8", grade="industrial", form="powder", purity=99.2,
       un=None, dg="non-DG", pg=None, ghs=["GHS07"], flash=None, storage="SC-8",
       price=245, uom="kg", moq=1000, lead=10, origin="TR",
       packs=[_pack("25 kg bag", 25, per_pallet=40), _pack("1000 kg jumbo", 1000)],
       supplier="s1", docs=["SDS", "CoA"]),
    _P(id="p-1007", sku="PAC-30", name="Poly Aluminium Chloride (PAC) 30%", segment="S11.3",
       cas="1327-41-9", grade="industrial", form="liquid", purity=30.0,
       un=None, dg="non-DG", pg=None, ghs=["GHS05"], flash=None, storage="SC-8",
       price=132, uom="kg", moq=1250, lead=7, origin="IN",
       packs=[_pack("1250 kg IBC", 1250)],
       supplier="s1", docs=["SDS", "CoA"]),
    _P(id="p-1008", sku="TIO2-R902", name="Titanium Dioxide Rutile R-902", segment="S14",
       cas="13463-67-7", grade="industrial", form="powder", purity=93.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=2450, uom="kg", moq=1000, lead=21, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s3", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-1009", sku="GCC-10", name="Calcium Carbonate GCC 10 micron", segment="S14",
       cas="471-34-1", grade="industrial", form="powder", purity=98.5,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=78, uom="kg", moq=1000, lead=10, origin="EG",
       packs=[_pack("25 kg bag", 25, per_pallet=40), _pack("1000 kg jumbo", 1000)],
       supplier="s3", docs=["SDS", "CoA"]),
    _P(id="p-1010", sku="METH-998", name="Methanol 99.8%", segment="S12.2",
       cas="67-56-1", grade="technical", form="liquid", purity=99.8,
       un="1230", dg="3", pg="II", ghs=["GHS02", "GHS06"], flash=11.0, storage="SC-3",
       price=410, uom="kg", moq=1000, lead=7, origin="SA",
       packs=[_pack("200 L drum", 167, "1H1/Y1.8/150"), _pack("1000 kg IBC", 1000, "31HA1/Y/100")],
       supplier="s1", docs=["SDS", "CoA"], note="Highly flammable, toxic. SC-3 fire-rated store, ATEX area."),
    _P(id="p-1011", sku="IPA-998", name="Isopropanol 99.8%", segment="S12.2",
       cas="67-63-0", grade="technical", form="liquid", purity=99.8,
       un="1219", dg="3", pg="II", ghs=["GHS02", "GHS07"], flash=12.0, storage="SC-3",
       price=880, uom="kg", moq=200, lead=7, origin="IN",
       packs=[_pack("200 L drum", 158, "1H1/Y1.8/150")],
       supplier="s1", docs=["SDS", "CoA"]),
    _P(id="p-1012", sku="ETAC-99", name="Ethyl Acetate 99%", segment="S12.2",
       cas="141-78-6", grade="technical", form="liquid", purity=99.0,
       un="1173", dg="3", pg="II", ghs=["GHS02", "GHS07"], flash=-4.0, storage="SC-3",
       price=1120, uom="kg", moq=200, lead=9, origin="IN",
       packs=[_pack("200 L drum", 180, "1H1/Y1.8/150")],
       supplier="s3", docs=["SDS", "CoA"]),
    _P(id="p-1013", sku="LIMO-BIO", name="d-Limonene (bio-based solvent)", segment="S12.5",
       cas="5989-27-5", grade="technical", form="liquid", purity=95.0,
       un="3082", dg="9", pg="III", ghs=["GHS07", "GHS09"], flash=48.0, storage="SC-8",
       price=2650, uom="kg", moq=200, lead=18, origin="BR",
       packs=[_pack("200 L drum", 168, "1H1/Y1.8/150")],
       supplier="s3", docs=["SDS", "CoA", "TDS"], note="Bio-based replacement for halogenated degreasers."),
    _P(id="p-1014", sku="HDPE-50018", name="HDPE Blow Moulding 50018N", segment="S13.1",
       cas="9002-88-4", grade="industrial", form="granule", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1180, uom="kg", moq=1000, lead=14, origin="SA",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s3", docs=["SDS", "CoA", "TDS"], mfi=8.0),
    _P(id="p-1015", sku="EPX-E128", name="Epoxy Resin E-128", segment="S13.4",
       cas="25068-38-6", grade="industrial", form="liquid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=["GHS07", "GHS09"], flash=200.0, storage="SC-8",
       price=2180, uom="kg", moq=220, lead=21, origin="CN",
       packs=[_pack("220 kg drum", 220)],
       supplier="s3", docs=["SDS", "CoA", "TDS"], pot_life=45),

    # ========================= S2 SPECIALTY ================================ #
    _P(id="p-2001", sku="LABSA-90", name="LABSA 90%", segment="S20",
       cas="25155-30-0", grade="technical", form="liquid", purity=90.0,
       un=None, dg="non-DG", pg=None, ghs=["GHS05"], flash=None, storage="SC-8",
       price=1290, uom="kg", moq=1000, lead=10, origin="IN",
       packs=[_pack("210 kg drum", 210), _pack("1100 kg IBC", 1100)],
       supplier="s1", docs=["SDS", "CoA", "TDS"], note="Primary anionic for liquid detergent."),
    _P(id="p-2002", sku="SLES-70-2EO", name="SLES 70% (2EO)", segment="S20",
       cas="68891-38-3", grade="technical", form="paste", purity=70.0,
       un=None, dg="non-DG", pg=None, ghs=["GHS07"], flash=None, storage="SC-8",
       price=1085, uom="kg", moq=1000, lead=10, origin="IN",
       packs=[_pack("220 kg drum", 220), _pack("1100 kg IBC", 1100)],
       supplier="s1", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-2003", sku="CAPB-30", name="Cocamidopropyl Betaine 30%", segment="S20",
       cas="61789-40-0", grade="technical", form="liquid", purity=30.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1340, uom="kg", moq=200, lead=12, origin="IN",
       packs=[_pack("200 kg drum", 200)],
       supplier="s3", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-2004", sku="PAM-ANION", name="Anionic Polyacrylamide Flocculant", segment="S23",
       cas="9003-05-8", grade="industrial", form="granule", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1650, uom="kg", moq=500, lead=14, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s1", docs=["SDS", "CoA", "TDS"], note="Effluent clarifier. Pair with PAC for best result."),
    _P(id="p-2005", sku="ANTISC-RO200", name="RO Antiscalant RO-200", segment="S23",
       cas=None, grade="industrial", form="liquid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=["GHS07"], flash=None, storage="SC-8",
       price=780, uom="kg", moq=25, lead=7, origin="AE",
       packs=[_pack("25 kg can", 25)],
       supplier="s4", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-2006", sku="CIP-ALK", name="CIP Alkaline Detergent 30%", segment="S24",
       cas=None, grade="industrial", form="liquid", purity=30.0,
       un="1719", dg="8", pg="III", ghs=["GHS05"], flash=None, storage="SC-2",
       price=395, uom="kg", moq=200, lead=6, origin="NG",
       packs=[_pack("200 L drum", 220, "1H1/Y1.8/150"), _pack("1000 kg IBC", 1000, "31HA1/Y/100")],
       supplier="s2", docs=["SDS", "CoA", "TDS"], note="Food-contact capable; request food-grade certificate for S26 end use."),
    _P(id="p-2007", sku="DESCAL-HNO3", name="Nitric Acid Passivation Descaler", segment="S24",
       cas=None, grade="industrial", form="liquid", purity=25.0,
       un="2031", dg="8", pg="II", ghs=["GHS03", "GHS05"], flash=None, storage="SC-1",
       price=455, uom="kg", moq=200, lead=6, origin="NG",
       packs=[_pack("200 L drum", 250, "1H1/Y1.8/150")],
       supplier="s2", docs=["SDS", "CoA", "TDS"], note="Oxidising acid, SC-1. Never with organics or flammables."),
    _P(id="p-2008", sku="CITRIC-FOOD", name="Citric Acid Monohydrate (FOOD grade)", segment="S26",
       cas="77-92-9", grade="food", form="granule", purity=99.5,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1450, uom="kg", moq=500, lead=14, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s4", docs=["SDS", "CoA", "GRADE_CERT", "ALLERGEN"], note="FSSC/Halal/Kosher certificates on file."),
    _P(id="p-2009", sku="CITRIC-TECH", name="Citric Acid Monohydrate (TECHNICAL)", segment="S26",
       cas="77-92-9", grade="technical", form="granule", purity=98.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1180, uom="kg", moq=500, lead=10, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s3", docs=["SDS", "CoA"], note="NOT for food or pharma use -- the grade gate will block it."),
    _P(id="p-2010", sku="HYD-OIL-46", name="Hydraulic Oil ISO VG 46", segment="S27",
       cas=None, grade="industrial", form="liquid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=210.0, storage="SC-8",
       price=980, uom="l", moq=20, lead=5, origin="NL",
       packs=[_pack("20 L can", 18), _pack("200 L drum", 180)],
       supplier="s4", docs=["SDS", "CoA", "TDS"], viscosity="ISO VG 46"),
    _P(id="p-2011", sku="GLYPH-41", name="Glyphosate 41% SL", segment="S30",
       cas="1071-83-6", grade="technical", form="liquid", purity=41.0,
       un="3016", dg="6.1", pg="III", ghs=["GHS07", "GHS09"], flash=None, storage="SC-6",
       packs=[_pack("20 L can", 22), _pack("200 L drum", 220)],
       price=2350, uom="l", moq=200, lead=18, origin="CN",
       supplier="s3", docs=["SDS", "CoA", "LICENCE"], note="LICENCE-GATED: valid pesticide licence required on both buyer and supplier."),
    _P(id="p-2012", sku="NAOH-AR", name="Sodium Hydroxide AR Grade", segment="S31",
       cas="1310-73-2", grade="AR", form="pellet", purity=99.0,
       un="1823", dg="8", pg="II", ghs=["GHS05"], flash=None, storage="SC-2",
       price=680, uom="kg", moq=5, lead=10, origin="DE",
       packs=[_pack("1 kg bottle", 1), _pack("2.5 kg bottle", 2.5)],
       supplier="s4", docs=["SDS", "CoA"], note="Laboratory reagent for QC titration."),

    # ========================= S3 EQUIPMENT ================================ #
    _P(id="p-3001", sku="RX-SS316-5000", name="5,000 L SS316L Jacketed Reactor + High-Shear Mixer",
       segment="S34", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=48500, uom="unit", moq=1, lead=70, origin="IN",
       packs=[_pack("1 unit", 3200)],
       supplier="s5", docs=["CE_DECL", "TEST_CERT_3_1"],
       equipment=dict(capacity="5000 L", moc="SS316L", power="415V 3ph 50Hz / 22 kW",
                      certs=["PED", "CE"], condition="new", warranty=12, install=True),
       note="The anchor asset of a liquid-washing line."),
    _P(id="p-3002", sku="PUMP-AODD-2", name="2\" AODD Diaphragm Pump, PTFE diaphragms",
       segment="S37", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=1850, uom="unit", moq=1, lead=21, origin="IT",
       packs=[_pack("1 unit", 62)],
       supplier="s5", docs=["CE_DECL", "TEST_CERT_3_1"],
       equipment=dict(capacity="up to 568 l/min", moc="Alu body / PTFE", power="compressed air",
                      certs=["ATEX", "CE"], condition="new", warranty=24, install=False),
       note="Air-driven, sealless -- the correct choice for corrosive and flammable duty."),
    _P(id="p-3003", sku="PUMP-MAG-PP", name="Magnetic Drive Centrifugal Pump, PP",
       segment="S37", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=2400, uom="unit", moq=1, lead=28, origin="IN",
       packs=[_pack("1 unit", 48)],
       supplier="s5", docs=["CE_DECL"],
       equipment=dict(capacity="25 m3/h @ 24 m", moc="PP / PTFE", power="415V 3ph 50Hz / 4 kW",
                      certs=["CE"], condition="new", warranty=12, install=False),
       note="No dynamic seal means no leak path for acids and caustic."),
    _P(id="p-3004", sku="PHE-PLATE-40", name="Plate Heat Exchanger, 40 plates",
       segment="S36", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=6900, uom="unit", moq=1, lead=35, origin="IN",
       packs=[_pack("1 unit", 310)],
       supplier="s5", docs=["CE_DECL", "TEST_CERT_3_1"],
       equipment=dict(capacity="420 kW @ 10 m3/h", moc="SS316 plates / NBR gaskets",
                      power="n/a", certs=["PED", "CE"], condition="new", warranty=24, install=False)),
    _P(id="p-3005", sku="TX-PH-ATEX", name="pH/ORP Transmitter, ATEX",
       segment="S38", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=740, uom="unit", moq=1, lead=14, origin="DE",
       packs=[_pack("1 unit", 3)],
       supplier="s5", docs=["CE_DECL", "CALIBRATION"],
       equipment=dict(capacity="0-14 pH, 2-wire 4-20 mA", moc="PP body / glass electrode",
                      power="24V DC", certs=["ATEX", "CE"], condition="new", warranty=24, install=False),
       note="Ships with a calibration certificate. Annual recalibration recommended."),
    _P(id="p-3006", sku="FILL-DRUM-200", name="200 L Drum Filling Station with load cells",
       segment="S39", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=11800, uom="unit", moq=1, lead=42, origin="IN",
       packs=[_pack("1 unit", 640)],
       supplier="s5", docs=["CE_DECL"],
       equipment=dict(capacity="60 drums/h, +/- 0.2% accuracy", moc="SS304 frame / PTFE wetted",
                      power="415V 3ph 50Hz / 3 kW", certs=["CE", "ATEX"], condition="new",
                      warranty=12, install=True)),
    _P(id="p-3007", sku="FP-800", name="Filter Press 800 x 800, 30 plates",
       segment="S35", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=16400, uom="unit", moq=1, lead=56, origin="IN",
       packs=[_pack("1 unit", 2100)],
       supplier="s5", docs=["CE_DECL"],
       equipment=dict(capacity="2.4 m3 cake volume", moc="PP plates / SS304 frame",
                      power="415V 3ph 50Hz / 5.5 kW", certs=["CE"], condition="new",
                      warranty=12, install=True)),

    # ======================== S4 CONSUMABLES =============================== #
    _P(id="p-4001", sku="DRUM-HDPE-220", name="220 L HDPE Drum, UN-rated 1H1/Y1.8/150",
       segment="S45", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=62, uom="unit", moq=50, lead=7, origin="NG",
       packs=[_pack("1 drum", 9)], un_rating="1H1/Y1.8/150",
       supplier="s2", docs=["TEST_CERT_3_1"], note="UN-rated for Class 8 and Class 3 fills. Certification mandatory for DG."),
    _P(id="p-4002", sku="IBC-1000-UN", name="1,000 L IBC, UN-rated 31HA1/Y1.8/100",
       segment="S45", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=310, uom="unit", moq=10, lead=10, origin="NG",
       packs=[_pack("1 IBC", 62)], un_rating="31HA1/Y1.8/100",
       supplier="s2", docs=["TEST_CERT_3_1"]),
    _P(id="p-4003", sku="GLOVE-NIT-CHEM", name="Nitrile Chemical Gauntlet, EN 374 Type A",
       segment="S46", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=14, uom="unit", moq=100, lead=5, origin="MY",
       packs=[_pack("1 pair", 0.1), _pack("box of 100", 10)], standard="EN ISO 374-1 Type A",
       supplier="s4", docs=["CE_DECL"], note="Required for any handling of SC-1 or SC-2 materials."),
    _P(id="p-4004", sku="COVERALL-56", name="Coverall Type 5/6, hooded",
       segment="S46", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=9, uom="unit", moq=100, lead=5, origin="CN",
       packs=[_pack("1 suit", 0.2), _pack("case of 50", 10)], standard="EN ISO 13982-1 / EN 13034",
       supplier="s4", docs=["CE_DECL"]),
    _P(id="p-4005", sku="FBAG-PP-25", name="Filter Bag PP 25 micron, size 2",
       segment="S47", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=11, uom="unit", moq=50, lead=7, origin="IN",
       packs=[_pack("1 bag", 0.1), _pack("pack of 50", 5)], micron=25,
       supplier="s4", docs=["TDS"], note="Highest-frequency consumable on a liquid line. Reorder at 60% depletion."),
    _P(id="p-4006", sku="GSK-SW-DN50", name="Spiral Wound Gasket SS316/Graphite DN50 PN16",
       segment="S48", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=18, uom="unit", moq=20, lead=7, origin="IN",
       packs=[_pack("1 gasket", 0.2), _pack("box of 20", 4)], compat="acids, alkalis, solvents to 200 C",
       supplier="s5", docs=["TEST_CERT_3_1"]),

    # ========================= S6 SECONDARY ================================ #
    _P(id="p-6001", sku="IPA-RECOV", name="Recovered IPA (re-distilled, 97%)",
       segment="S67", cas="67-63-0", grade="technical", form="liquid", purity=97.0,
       un="1219", dg="3", pg="II", ghs=["GHS02", "GHS07"], flash=12.0, storage="SC-3",
       price=520, uom="kg", moq=200, lead=7, origin="NG",
       packs=[_pack("200 L drum", 158, "1H1/Y1.8/150")],
       supplier="s4", docs=["SDS", "CoA"],
       disclosure="97% purity vs 99.8% virgin spec; trace acetone 0.8% and water 1.9%. "
                  "Suitable for cleaning, not for formulation.",
       recovery="Solvent recovery service, Lagos industrial cluster",
       note="41% cheaper than virgin. Cannot be recommended into grade-gated end uses."),
    _P(id="p-6002", sku="TIO2-OFFSPEC", name="Titanium Dioxide Rutile (off-spec brightness)",
       segment="S66", cas="13463-67-7", grade="industrial", form="powder", purity=91.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=1780, uom="kg", moq=1000, lead=7, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)],
       supplier="s3", docs=["SDS", "CoA"],
       disclosure="Brightness 93.1% vs 96% spec; oil absorption within limits. "
                  "Fit for primers and putty, not for topcoats.",
       note="Off-spec stock. Deviation disclosure is mandatory and cannot be waived."),

    # ==================================================================== #
    # Alternate sources. Depth matters: plan/02 requires >=3 qualified quotes
    # per RFQ line before a lot can be awarded, so every launch segment needs
    # at least three distinct suppliers behind it.
    # ==================================================================== #
    _P(id="p-2013", sku="SLES-70-3EO-B", name="SLES 70% (3EO) — alternate source", segment="S20",
       cas="68891-38-3", grade="technical", form="paste", purity=70.0,
       un=None, dg="non-DG", pg=None, ghs=["GHS07"], flash=None, storage="SC-8",
       price=1042, uom="kg", moq=1100, lead=12, origin="NG",
       packs=[_pack("220 kg drum", 220)], supplier="s2", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-2014", sku="APG-0810", name="Alkyl Polyglucoside APG 0810", segment="S20",
       cas="68515-73-1", grade="technical", form="liquid", purity=60.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=2150, uom="kg", moq=200, lead=18, origin="DE",
       packs=[_pack("200 kg drum", 200)], supplier="s4", docs=["SDS", "CoA", "TDS"],
       note="Non-ionic, readily biodegradable. Premium green formulation choice."),
    _P(id="p-1016", sku="CAUS-FL99-B", name="Caustic Soda Flakes 99% — alternate source", segment="S11.2",
       cas="1310-73-2", grade="industrial", form="flake", purity=99.0,
       un="1823", dg="8", pg="II", ghs=["GHS05"], flash=None, storage="SC-2",
       price=512, uom="kg", moq=1000, lead=14, origin="EG",
       packs=[_pack("25 kg bag", 25, per_pallet=40)], supplier="s3", docs=["SDS", "CoA"]),
    _P(id="p-1017", sku="H3PO4-85", name="Phosphoric Acid 85% (technical)", segment="S11.1",
       cas="7664-38-2", grade="technical", form="liquid", purity=85.0,
       un="1805", dg="8", pg="III", ghs=["GHS05"], flash=None, storage="SC-1",
       price=520, uom="kg", moq=350, lead=12, origin="MA",
       packs=[_pack("350 kg drum", 350, "1H1/Y1.8/150")], supplier="s3", docs=["SDS", "CoA"]),
    _P(id="p-1018", sku="SMBS-97", name="Sodium Metabisulphite 97%", segment="S11.3",
       cas="7681-57-4", grade="industrial", form="powder", purity=97.0,
       un="2695", dg="8", pg="III", ghs=["GHS05", "GHS07"], flash=None, storage="SC-1",
       price=430, uom="kg", moq=1000, lead=14, origin="DE",
       packs=[_pack("25 kg bag", 25, per_pallet=40)], supplier="s3", docs=["SDS", "CoA"],
       note="Dechlorination and oxygen scavenging. Releases SO2 with acid."),
    _P(id="p-2015", sku="OSCAV-HYD", name="Oxygen Scavenger / Corrosion Inhibitor", segment="S23",
       cas=None, grade="industrial", form="liquid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=["GHS07"], flash=None, storage="SC-8",
       price=690, uom="kg", moq=25, lead=7, origin="AE",
       packs=[_pack("25 kg can", 25)], supplier="s2", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-1019", sku="TIO2-ANAT", name="Titanium Dioxide Anatase A-100", segment="S14",
       cas="13463-67-7", grade="industrial", form="powder", purity=98.0,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=2280, uom="kg", moq=1000, lead=18, origin="CN",
       packs=[_pack("25 kg bag", 25, per_pallet=40)], supplier="s1", docs=["SDS", "CoA", "TDS"]),
    _P(id="p-1020", sku="GCC-15-B", name="Calcium Carbonate GCC 15 micron", segment="S14",
       cas="471-34-1", grade="industrial", form="powder", purity=97.5,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=72, uom="kg", moq=1000, lead=9, origin="EG",
       packs=[_pack("25 kg bag", 25, per_pallet=40)], supplier="s4", docs=["SDS", "CoA"]),
    _P(id="p-1021", sku="ETHANOL-96", name="Ethanol 96% (denatured, industrial)", segment="S12.2",
       cas="64-17-5", grade="technical", form="liquid", purity=96.0,
       un="1170", dg="3", pg="II", ghs=["GHS02"], flash=13.0, storage="SC-3",
       price=1250, uom="l", moq=200, lead=8, origin="NG",
       packs=[_pack("200 L drum", 157, "1H1/Y1.8/150")], supplier="s2", docs=["SDS", "CoA"]),

    # --- equipment: three competing fabricators per lot ---------------- #
    _P(id="p-3008", sku="RX-SS316-3000-B", name="3,000 L SS316L Jacketed Reactor + Anchor Agitator",
       segment="S34", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=31200, uom="unit", moq=1, lead=63, origin="IN", packs=[_pack("1 unit", 2400)],
       supplier="s6", docs=["CE_DECL", "TEST_CERT_3_1"],
       equipment=dict(capacity="3000 L", moc="SS316L", power="415V 3ph 50Hz / 15 kW",
                      certs=["PED", "CE"], condition="new", warranty=12, install=True)),
    _P(id="p-3009", sku="RX-GLA-2000", name="2,000 L Glass-Lined Reactor, jacketed",
       segment="S34", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=27800, uom="unit", moq=1, lead=77, origin="ZA", packs=[_pack("1 unit", 2900)],
       supplier="s7", docs=["CE_DECL"],
       equipment=dict(capacity="2000 L", moc="GLA (glass-lined steel)",
                      power="415V 3ph 50Hz / 11 kW", certs=["CE"], condition="new",
                      warranty=12, install=False),
       note="Correct choice for strong acids where stainless is attacked."),
    _P(id="p-3010", sku="PUMP-LOBE-15", name="1.5\" Sanitary Lobe Pump, SS316",
       segment="S37", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=3950, uom="unit", moq=1, lead=28, origin="IN", packs=[_pack("1 unit", 78)],
       supplier="s6", docs=["CE_DECL"],
       equipment=dict(capacity="12 m3/h", moc="SS316 / EPDM", power="415V 3ph 50Hz / 3 kW",
                      certs=["CE"], condition="new", warranty=12, install=False)),
    _P(id="p-3011", sku="PUMP-SCREW-PROG", name="Progressive Cavity Pump, stator NBR",
       segment="S37", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=4400, uom="unit", moq=1, lead=35, origin="ZA", packs=[_pack("1 unit", 120)],
       supplier="s7", docs=["CE_DECL"],
       equipment=dict(capacity="8 m3/h @ 12 bar", moc="SS304 rotor / NBR stator",
                      power="415V 3ph 50Hz / 5.5 kW", certs=["CE"], condition="new",
                      warranty=12, install=False)),
    _P(id="p-3012", sku="TX-COND-4P", name="4-Electrode Conductivity Transmitter",
       segment="S38", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=820, uom="unit", moq=1, lead=14, origin="IN", packs=[_pack("1 unit", 4)],
       supplier="s6", docs=["CE_DECL", "CALIBRATION"],
       equipment=dict(capacity="0.01 uS/cm to 2000 mS/cm", moc="PPS body / graphite electrodes",
                      power="24V DC", certs=["CE"], condition="new", warranty=24, install=False)),
    _P(id="p-3013", sku="TX-FLOW-MAG", name="Magnetic Flow Meter DN50",
       segment="S38", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=1450, uom="unit", moq=1, lead=21, origin="ZA", packs=[_pack("1 unit", 12)],
       supplier="s7", docs=["CE_DECL", "CALIBRATION"],
       equipment=dict(capacity="DN50, 0.5-10 m/s, +/-0.5%", moc="PTFE liner / SS316 electrodes",
                      power="24V DC", certs=["CE"], condition="new", warranty=24, install=False)),
    _P(id="p-3014", sku="FILL-IBC-1000", name="1,000 L IBC Filling Station",
       segment="S39", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=18900, uom="unit", moq=1, lead=49, origin="IN", packs=[_pack("1 unit", 900)],
       supplier="s6", docs=["CE_DECL"],
       equipment=dict(capacity="12 IBC/h, +/- 0.3%", moc="SS304 / PTFE",
                      power="415V 3ph 50Hz / 4 kW", certs=["CE"], condition="new",
                      warranty=12, install=True)),
    _P(id="p-3015", sku="FILL-BOTTLE-4WAY", name="4-Way Bottle Filling & Capping Monobloc",
       segment="S39", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=42500, uom="unit", moq=1, lead=84, origin="ZA", packs=[_pack("1 unit", 2600)],
       supplier="s7", docs=["CE_DECL"],
       equipment=dict(capacity="3000 bph, 500-1000 mL", moc="SS304 / PET",
                      power="415V 3ph 50Hz / 7.5 kW", certs=["CE"], condition="new",
                      warranty=12, install=True)),
    _P(id="p-3016", sku="DECANTER-CENT", name="Decanter Centrifuge, 2-phase",
       segment="S35", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=68000, uom="unit", moq=1, lead=98, origin="IN", packs=[_pack("1 unit", 4200)],
       supplier="s6", docs=["CE_DECL"],
       equipment=dict(capacity="6 m3/h feed", moc="SS316L bowl / duplex scroll",
                      power="415V 3ph 50Hz / 45 kW", certs=["CE", "ATEX"], condition="new",
                      warranty=12, install=True)),
    _P(id="p-3017", sku="DRYER-FBD-500", name="Fluid Bed Dryer 500 L",
       segment="S35", cas=None, grade=None, form="equipment", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage=None,
       price=39500, uom="unit", moq=1, lead=70, origin="ZA", packs=[_pack("1 unit", 3100)],
       supplier="s7", docs=["CE_DECL"],
       equipment=dict(capacity="500 L batch", moc="SS316 contact parts",
                      power="415V 3ph 50Hz / 30 kW", certs=["CE", "ATEX"], condition="new",
                      warranty=12, install=True)),

    # --- consumables: three vendors per line --------------------------- #
    _P(id="p-4007", sku="DRUM-STEEL-210", name="210 L Steel Drum, UN-rated 1A1/Y1.5/150",
       segment="S45", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=185, uom="unit", moq=20, lead=10, origin="NG",
       packs=[_pack("1 drum", 22)], un_rating="1A1/Y1.5/150", supplier="s8",
       docs=["TEST_CERT_3_1"], note="Flammables and solvents. Prefer steel over HDPE for Class 3."),
    _P(id="p-4008", sku="JERRY-25", name="25 L Jerry Can, UN-rated 1H1/Y1.5/100",
       segment="S45", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=48, uom="unit", moq=50, lead=6, origin="NG",
       packs=[_pack("1 can", 1.4)], un_rating="1H1/Y1.5/100", supplier="s9",
       docs=["TEST_CERT_3_1"]),
    _P(id="p-4009", sku="BOOT-S5", name="Safety Boot S5 SRC, steel toe",
       segment="S46", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=85, uom="unit", moq=12, lead=7, origin="NG",
       packs=[_pack("1 pair", 2)], standard="EN ISO 20345 S5 SRC", supplier="s8",
       docs=["CE_DECL"], note="Chemical-resistant PVC. Mandatory in bunded handling areas."),
    _P(id="p-4010", sku="FSHIELD-VISOR", name="Face Shield with chemical visor",
       segment="S46", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=24, uom="unit", moq=25, lead=5, origin="NG",
       packs=[_pack("1 shield", 0.3)], standard="EN 166 3-B", supplier="s9", docs=["CE_DECL"]),
    _P(id="p-4011", sku="FCART-5", name="Cartridge Filter 5 micron, 20 inch",
       segment="S47", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=28, uom="unit", moq=24, lead=7, origin="IN",
       packs=[_pack("1 cartridge", 0.4)], micron=5, supplier="s8", docs=["TDS"]),
    _P(id="p-4012", sku="FBAG-PE-50", name="Filter Bag PE 50 micron, size 1",
       segment="S47", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=9, uom="unit", moq=50, lead=6, origin="NG",
       packs=[_pack("1 bag", 0.08)], micron=50, supplier="s9", docs=["TDS"]),
    _P(id="p-4013", sku="GSK-PTFE-DN50", name="PTFE Envelope Gasket DN50 PN16",
       segment="S48", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=26, uom="unit", moq=20, lead=7, origin="NG",
       packs=[_pack("1 gasket", 0.15)], compat="acids, alkalis, solvents to 180 C",
       supplier="s8", docs=["TEST_CERT_3_1"]),
    _P(id="p-4014", sku="GSK-EPDM-DN50", name="EPDM Gasket DN50 PN16",
       segment="S48", cas=None, grade=None, form="solid", purity=None,
       un=None, dg="non-DG", pg=None, ghs=[], flash=None, storage="SC-8",
       price=8, uom="unit", moq=20, lead=5, origin="NG",
       packs=[_pack("1 gasket", 0.1)], compat="alkalis, hot water, dilute acids",
       supplier="s9", docs=["TDS"],
       note="Cheaper than PTFE but NOT for solvents or strong acids — see compatibility."),
]

# --------------------------------------------------------------------------- #
# Line templates -- the "we sell the line" differentiator from plan/03.
# Maps a Taxonomy B application code to the roles a working line needs.
# --------------------------------------------------------------------------- #
LINE_TEMPLATES: dict[str, dict] = {
    "B02": {
        "name": "Liquid detergent / washing line",
        "typical": "5,000 L batch, 2 shifts",
        "roles": [
            ("Reactor / mixing vessel", "p-3001"),
            ("Surfactant - primary anionic", "p-2001"),
            ("Surfactant - secondary", "p-2002"),
            ("Amphoteric / foam booster", "p-2003"),
            ("pH adjuster (alkali)", "p-1002"),
            ("Transfer pump (corrosive duty)", "p-3002"),
            ("In-line pH control", "p-3005"),
            ("Filling station", "p-3006"),
            ("Packaging - 200 L drum, UN-rated", "p-4001"),
            ("PPE - chemical gloves", "p-4003"),
            ("PPE - coveralls", "p-4004"),
            ("Filtration consumable", "p-4005"),
        ],
    },
    "B01": {
        "name": "Water treatment & effluent plant",
        "typical": "Clarifier + RO train",
        "roles": [
            ("Coagulant", "p-1007"),
            ("Flocculant", "p-2004"),
            ("Biocide / oxidiser", "p-1005"),
            ("pH adjuster (acid)", "p-1003"),
            ("RO antiscalant", "p-2005"),
            ("Dosing pump (sealless)", "p-3003"),
            ("pH/ORP instrumentation", "p-3005"),
            ("Clarification - filter press", "p-3007"),
            ("PPE - chemical gloves", "p-4003"),
            ("Filtration consumable", "p-4005"),
        ],
    },
}

SUPPLIERS: dict[str, dict] = {
    "s1": {"org_id": "s1", "name": "Coastal Chem Distributors", "verification_tier": "T3",
           "country": "NG", "score": 4.7, "licences": {}},
    "s2": {"org_id": "s2", "name": "Lagos Industrial Supply", "verification_tier": "T3",
           "country": "NG", "score": 4.5, "licences": {}},
    "s3": {"org_id": "s3", "name": "Meridian Chemical Traders", "verification_tier": "T2",
           "country": "AE", "score": 4.1, "licences": {}},
    "s4": {"org_id": "s4", "name": "Harmattan Lab & MRO", "verification_tier": "T3",
           "country": "NG", "score": 4.8, "licences": {}},
    "s5": {"org_id": "s5", "name": "Niger Process Equipment", "verification_tier": "T3",
           "country": "IN", "score": 4.3, "licences": {}},
    "s6": {"org_id": "s6", "name": "Delta Process Fabricators", "verification_tier": "T3",
           "country": "IN", "score": 4.4, "licences": {}},
    "s7": {"org_id": "s7", "name": "Vantage Plant Systems", "verification_tier": "T2",
           "country": "ZA", "score": 4.0, "licences": {}},
    "s8": {"org_id": "s8", "name": "Sahel Safety & Packaging", "verification_tier": "T3",
           "country": "NG", "score": 4.6, "licences": {}},
    "s9": {"org_id": "s9", "name": "Guinea Gulf MRO", "verification_tier": "T2",
           "country": "NG", "score": 3.9, "licences": {}},
}

BY_ID: dict[str, dict] = {p["id"]: p for p in PRODUCTS}

# --------------------------------------------------------------------------- #
# Generated catalogue -- expands the substance library to the target SKU count.
# Hand-authored anchors above are preserved verbatim (tests and line templates
# reference them by id), so generated rows are appended with a distinct id range.
# --------------------------------------------------------------------------- #
import catalog_gen  # noqa: E402

CHEM_PILLARS = ("S1", "S2", "S6")
CHEMICAL_SKU_TARGET = 1000

# NOTE: pillar membership cannot be inferred from the segment code prefix.
# S30/S32/S33 belong to the S2 pillar even though they start with "S3".
import os, sys as _sys, json as _json
_TAX_PATH = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                         "data", "taxonomy.json")
_SEG_PILLAR = {n["code"]: n["pillar"]
               for n in _json.load(open(_TAX_PATH))["taxonomies"]["A_category_tree"]
               if n.get("pillar")}


def is_chemical(product: dict) -> bool:
    """True when the product is a sourced chemical (pillars S1, S2, S6)."""
    return _SEG_PILLAR.get(product["segment"]) in CHEM_PILLARS


_anchor_chems = [p for p in PRODUCTS if is_chemical(p)]
_generate_count = max(0, CHEMICAL_SKU_TARGET - len(_anchor_chems))

PRODUCTS += catalog_gen.generate(
    target=_generate_count,
    used_skus={p["sku"] for p in PRODUCTS},
)

BY_ID = {p["id"]: p for p in PRODUCTS}
